In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset = pd.read_csv("bank-loan.csv")

In [4]:
dataset.head(4)

   age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0   41   3      17       12     176      9.3  11.359392  5.008608      1.0
1   27   1      10        6      31     17.3   1.362202  4.000798      0.0
2   40   1      15       14      55      5.5   0.856075  2.168925      0.0
3   41   1      15       14     120      2.9   2.658720  0.821280      0.0

In [5]:
dataset.shape

(850, 9)

In [6]:
dataset.isnull().sum()

age           0
ed            0
employ        0
address       0
income        0
debtinc       0
creddebt      0
othdebt       0
default     150
dtype: int64

In [7]:
# sns.heatmap(dataset.isnull())

In [8]:
dataset.drop(columns =["default"],inplace = True)
# /// mising value ko drop karne ke liye pura colum hi hata diya

In [9]:
dataset.dropna(inplace =True)
# ye pure data me se missing value hata deta hai

In [10]:
#              handling missing values
 #              (imputing category data)

In [11]:
# dataset.fillna(10) 
# is me jitna missing value me 10 but kar raha hai

In [27]:
dataset.fillna(method = "bfill")
# ye ka kar raha hai ki jo piche wale value ko aage wala pe fill kar raha jo khali hai

C:\Users\milan\AppData\Local\Temp\ipykernel_18568\925489389.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataset.fillna(method = "bfill")

     age  ed  employ  address  income  debtinc   creddebt   othdebt
0     41   3      17       12     176      9.3  11.359392  5.008608
1     27   1      10        6      31     17.3   1.362202  4.000798
2     40   1      15       14      55      5.5   0.856075  2.168925
3     41   1      15       14     120      2.9   2.658720  0.821280
4     24   2       2        0      28     17.3   1.787436  3.056564
..   ...  ..     ...      ...     ...      ...        ...       ...
845   34   1      12       15      32      2.7   0.239328  0.624672
846   32   2      12       11     116      5.7   4.026708  2.585292
847   48   1      13       11      38     10.8   0.722304  3.381696
848   35   2       1       11      24      7.8   0.417456  1.454544
849   37   1      20       13      41     12.9   0.899130  4.389870

[850 rows x 8 columns]

In [13]:
#                         scikit- learn

In [14]:
  dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       850 non-null    int64
 1   ed        850 non-null    int64
 2   employ    850 non-null    int64
 3   address   850 non-null    int64
 4   income    850 non-null    int64
 5   debtinc   850 non-null    float64
 6   creddebt  850 non-null    float64
 7   othdebt   850 non-null    float64
dtypes: float64(3), int64(5)
memory usage: 53.3 KB

In [23]:
dataset.select_dtypes(include = "float64").columns

Index(['debtinc', 'creddebt', 'othdebt'], dtype='object')

In [24]:
from sklearn.impute import SimpleImputer

In [25]:
si = SimpleImputer(strategy = "mean")

In [26]:
arr = si.fit_transform(dataset[['debtinc', 'creddebt', 'othdebt', 'default']])

KeyError: "['default'] not in index"

In [19]:
pd.DataFrame(arr)

NameError: name 'arr' is not defined

In [ ]:
# ye sklearn ye kiya hai ki jo jaha jaha missing value tha waha waha iska mean value put kar diya hai